### ISSUE TITLE
Can't download the New 3DS firmware package

### ISSUE THREAD

**Issue by TurdPooCharger** [DrHacknik/3DNUS#21]
When trying to download the USA region **11.7.0-40U** package with the **New 3DS** option selected, I can't find the new Health & Safety with Title ID of **0004001020021300**. 

I can find the Health & Safety for the old series that's **0004001000021300**. I went and tried deleting the entire 3DNUS folder, extract from archive for fresh program install, go through the startup with **RESET SETTINGS**, and chose nothing but **New 3DS** for **Default Titlelist**.

I also downloaded the 11.7.0-40U for the Old 3DS and crossed compared what I get with New 3DS in hash checks; the two packages are identical file for file. I think my copy of 3DNUS is failing to download for New 3DS stuff.

This was done on both v3.3 Stable and v.3.31 nightly for Windows x64 on my Windows 8.1 64-bit laptop.

Also, the individual title search and download feature doesn't work for me. I'll download the entire firmware package with a log dump and try downloading a single cia. 

<img width="402" alt="3dnus" src="https://user-images.githubusercontent.com/35666439/42668437-a9249ea0-861e-11e8-9130-f6e533797ae3.png">

**Comment by Sara06515** [comment]
I had the same issue with downloading 11.7.0-40U firmware for n3DS. I only realized the files were identical for both o3DS & n3DS after I tried to downgrade my n3DS from firmware 11.8 to 11.7 using wrong files and soft-bricked it. Major problem...

**Comment by TurdPooCharger** [comment]
@Sara06515, Stable release 3.3.2 with **2018_7_3_609pm_x##** is able to download the New 3DS files.

You may need to hurry before Nintendo turns on the CDN downloader kill switch on their servers. This is coming from the latest news regarding firmware 11.8.0-41.
